name = "ManifoldLearning"
uuid = "06eb3307-b2af-5a2a-abea-d33192699d32"
keywords = ["manifold learning", "dimensionality reduction", "nonlinear"]
license = "MIT"
desc = "A Julia package for nonlinear dimensionality reduction"
repository = "https://github.com/JuliaStats/ManifoldLearning.jl.git"
version = "0.8.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
Combinatorics = "^1"
Graphs = "^1.5"
MultivariateStats = "^0.9"
StatsAPI = "^1.2"
julia = "1.3"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs", "Statistics"]
